/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clock: typeof import('./components/ClockClockWhite/Clock.vue')['default']
    ClockClockWhite: typeof import('./components/ClockClockWhite/index.vue')['default']
    Config: typeof import('./components/Config.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ticks: typeof import('./components/ClockClockWhite/Ticks.vue')['default']
  }
}
